name: Move Issue to In Progress

on:
  issues:
    types: [labeled, assigned]

permissions:
  issues: write
  contents: write

jobs:
  move_assigned_card:
    runs-on: ubuntu-latest
    steps:
      - name: Move card to 'In Progress'
        uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: 'Python Code'  # Ensure this matches your project name
          column: 'In Progress'   # Ensure this is the correct column name
          action: 'update'
          token: ${{ secrets.PYTHONCODETOKEN }}  # Ensure this is passed correctly
